[phases.setup]
nixPkgs = ["ffmpeg", "gcc", "cmake", "git", "gnumake"]
aptPkgs = ["python3", "python3-pip", "python3-venv"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 main.py"
