[phases.setup]
nixPkgs = []
aptPkgs = ["python3-full", "python3-pip", "ffmpeg", "git", "build-essential", "cmake"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt --break-system-packages"]

[start]
cmd = "python3 main.py"
