[phases.setup]
nixPkgs = ["python311Full", "ffmpeg", "gcc", "cmake", "git", "gnumake"]

[phases.install]
cmds = ["python -m ensurepip --default-pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python main.py"
